### ISSUE TITLE
Content warning 

### ISSUE THREAD

**Issue by Jbithell** [wlibrarian/wlibrarian.github.io#20]
https://github.com/wlibrarian/wlibrarian.github.io/blob/0b04abcdd39af4238031f8401ad3eccf54164029/1v5/cabaret.html#L17

As updated in https://github.com/wlibrarian/wlibrarian.github.io/commit/0b04abcdd39af4238031f8401ad3eccf54164029

Why does a content warning apply? The article doesn't contain any of the aforementioned - is this a reference to content of the play?

**Comment by octogenary** [comment]
It's a reference to the contents of the play─most articles with content warnings for things aren't racist even if there's a racism tag─they're there because the articles refer to such matters.

I'm not sure why it was just committed, since it was in the original TeX source whence the website was generated.

**Comment by Jbithell** [comment]
Makes sense - there's no pornography in the version we did though, but looks good as it stands
